### ISSUE TITLE
ParserError when i use my own corpus

### ISSUE THREAD

**Issue by idrissbachali** [AdrienGuille/TOM#11]
I use my own corpus "french_corpus.csv "and i get this result when i use pandas to read my csv as corpus .
this error happens in corpus.py  ,exactly ,in this sentence  "self.data_frame = pandas.read_csv(source_file_path, sep='\t', encoding='utf-8')"

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

**Comment by BKaurHarpreet** [comment]
Event when I give my own filepath I face issue  "Key Error Text" and it is thrown at the point where corpus class is called and when self.data_frame['text'].tolist() is called

**Comment by AdrienGuille** [comment]
Hi,

This means that your corpus isn't formatted properly. For instance, "Key Error Text" means that the CSV file is missing the "text" column. Please check out the instructions here: https://github.com/AdrienGuille/TOM#load-and-prepare-a-textual-corpus

Cheers,
Adrien
