### ISSUE TITLE
Error when loading corpus

### ISSUE THREAD

**Issue by ghost** [AdrienGuille/TOM#2]
Hi,

i am looking forward to use this library. I like the opportunity to plot the Greene, Arun and Brunet-methods.

Today i wanted to test the library (in Python 2.7). I installed via pip.
`pip install tom_lib`

When i run the example code 
`corpus = Corpus(source_file_path='input/egc_lemmatized.csv',
                language='french',
                vectorization=vectorization,
                max_relative_frequency=max_tf,
                min_absolute_frequency=min_tf,
                preprocessor=preprocessor)`
from [topic_model.py
](https://github.com/AdrienGuille/TOM/blob/master/topic_model.py) i get a KeyError.

`pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)()
pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)()
pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)()
pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)()
KeyError: 'full_content'
`
The example csv-file from this repository is in a directory called input.

Am i missing something?

I'm looking forward to hearing from you.
## Python Version?

Also i think the source code is not intended by used with Python 3 at the moment? On pypi it says: 

> TOM (TOpic Modeling) is a Python 2.7 library for topic modeling and browsing.

on GitHub it says

> TOM (TOpic Modeling) is a Python 3 library for topic modeling and browsing, licensed under the MIT license.

When i try to run the example scripts in Python 3, it gives a SyntaxError:
`File "...python3.5/site-packages/tom_lib/utils.py", line 13
    print matrix[i, :]`

**Comment by AdrienGuille** [comment]
Hi,

Thank you for this feedback!

### Key error

The latest versions of TOM (0.2.x) assume a different structure for input CSV files, in particular the 'full_content' column has been renamed to 'text' while 'short_content' has been renamed to 'title'.

### Python version

Please note that, from now on, we only provide support for the Python 3 version of TOM. TOM 0.2.2 for Python 3 is available on PyPI (https://pypi.python.org/pypi/tom_lib).

Adrien
